package uz.mediasolutions.miticodeliverytelegrambot.enums;

public enum InvoiceStatusEnum {

    // YANGI OCHILGAN INVOICE HALI TO'LANMAGAN
    PENDING,

    // BEKOR QILINGAN INVOICE (BIZ TOMONIMIZDAN BEKOR QILINGAN)
    REJECTED,

    // QISMAN TO'LAGAN VA HOZIRDA HAM TO'LAYABDI
    PAYING,

    // INVOICE MUDDATI O'TIB KETGAN
    // PULNI QISMAN TO'LAGAN BO'LSA HAM MUDDATI O'TIB KETISHI MUMKIN
    EXPIRED,

    // TO'LAGAN
    PAID,

    // PUL QAYTARILISHINI KUTILYABDI
    PENDING_REFUND,

    // PUL QAYTARIB BERILDI
    REFUND,

    // TALABANI GURUHDAN CHIQARILGAN BO'LSA
    // VA UNING INVOICESIDA QOLDIQ BIZ HIZMAT QILMAGAN SUMMADA PUL QOLGAN BO'LSA
    // UNI BALANCEGA YOZIB QUYAMIZ. INVOICEDAN INVOICEDA PUL KO'CHIRGANDA SHU BALANCE KO'CHISHI MUMKIN
    RECALCULATE

}
