package uz.mediasolutions.miticodeliverytelegrambot.enums;

public enum StepName {
    MAIN_MENU,
    SEND_SUGGESTION_COMPLAINT,
    MENU_SETTINGS,
    CHANGE_NAME,
    CHANGE_LANGUAGE,
    CHANGE_PHONE_NUMBER,
    INCORRECT_PHONE_FORMAT,
    CHOOSE_PAYMENT,
    ORDER_REGISTER_PHONE,
    CHOOSE_FROM_MAIN_MENU,
    ORDER_REGISTER_NAME,
    INCORRECT_PHONE_FORMAT_1,
    LEAVE_COMMENT,
    SEND_ORDER_TO_CHANNEL,
    GO_TO_PAYMENT,
    IS_DELIVERY,
    ORDER_CHOOSE,
    PENDING_ORDER, LEAVE_COMMENT_1, ORDER_LOCATION
}
